default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  port: <%= ENV.fetch("POSTGRES_PORT", '5434') %>
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'password') %>

development:
  <<: *default
  database: project_01_development


test:
  <<: *default
  database: project_01_test

production:
  <<: *default
  database: project_01_production